"""
Integration Test: Verify All Shortcut Examples Work for Authenticated Users

Tests all examples from the shortcuts endpoint for authenticated users to ensure:
1. Intent detection works correctly
2. Responses are not generic fallback messages
3. All shortcuts provide meaningful responses
4. Uses real access token from database (ops@anvilcrypto.com)
5. Dynamically fetches shortcuts from API endpoint

CTO Engineering Framework Methodology:
- Problem Analysis: Verify all shortcut examples work for authenticated users
- Solution Design: Test each example dynamically from shortcuts endpoint
- Implementation: Fetch shortcuts from API, test each example with real token
- Verification: Check intent detection, response quality, and content relevance
- Quality Assurance: Ensure no generic fallbacks and meaningful responses

Generated by scripts/generate_user_tests.py
"""

import pytest
import pytest_asyncio
from httpx import AsyncClient, ASGITransport
from uuid import uuid4

from app.run import make_app

# Access token for ops@anvilcrypto.com (embedded from database)
ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Nlc3Npb25faWQiOiJxSEZBY1Mxd2RMN0lkWEx3aGQyb3pKYjdmeTFvd1lMUTZWci1OdkFJYWRFIiwiZXhwIjoxNzY3ODE3Mzk2fQ.qFnOS9hWQF4svpnxWe8YKDYFerQNKJSyGrYXhoSqHdQ"

# Generic fallback message that should NOT appear
GENERIC_FALLBACK_MESSAGE = (
    "I'm your AI assistant for DeFi! I can help with market analysis (Hunter AI), "
    "automated trading (ULTRA), lending rates, swaps, and more. "
    "Ask me about protocols, yields, risks, or how to get started. "
    "Sign up for full access to all features."
)


@pytest_asyncio.fixture
async def client():
    """Create test client."""
    app = make_app()
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        yield ac


@pytest_asyncio.fixture
async def conversation_id(client: AsyncClient):
    """Create or get conversation for authenticated user."""
    # Try to get existing conversation first
    response = await client.get(
        "/api/v1/user/chat/conversations",
        headers={"Authorization": f"Bearer {ACCESS_TOKEN}"},
    )
    
    if response.status_code == 200:
        data = response.json()
        # Handle ConversationListResponse format
        if isinstance(data, dict) and "conversations" in data:
            conversations = data["conversations"]
        elif isinstance(data, list):
            conversations = data
        else:
            conversations = []
        
        if conversations and len(conversations) > 0:
            conv = conversations[0]
            # Handle both dict and object format
            if isinstance(conv, dict):
                return conv["id"]
            else:
                return conv.id if hasattr(conv, "id") else str(conv)
    
    # Create new conversation
    response = await client.post(
        "/api/v1/user/chat/conversations",
        json={"title": "Test Conversation", "language": "en"},
        headers={"Authorization": f"Bearer {ACCESS_TOKEN}"},
    )
    
    if response.status_code == 201:
        return response.json()["id"]
    
    # Fallback: generate UUID (will be auto-created by endpoint)
    return str(uuid4())


@pytest_asyncio.fixture
async def shortcuts_data(client: AsyncClient):
    """
    Fetch shortcuts data dynamically from API endpoint.
    
    CTO Framework: Dynamic Data Fetching
    - Fetches shortcuts from /api/v1/chat/shortcuts?lang=en
    - Ensures tests always use latest shortcut definitions
    - No hardcoded shortcuts in test code
    """
    response = await client.get("/api/v1/chat/shortcuts?lang=en")
    assert response.status_code == 200, f"Failed to fetch shortcuts: {response.status_code}"
    data = response.json()
    
    # Verify structure
    assert "shortcuts" in data, "Response missing 'shortcuts' key"
    assert isinstance(data["shortcuts"], list), "Shortcuts must be a list"
    assert len(data["shortcuts"]) > 0, "No shortcuts found"
    
    return data["shortcuts"]


@pytest.mark.asyncio
@pytest.mark.integration
async def test_user_shortcut_examples_detect_correct_intent(
    client: AsyncClient,
    shortcuts_data: list,
    conversation_id: str,
):
    """
    Test that all shortcut examples detect the correct intent for authenticated users.
    
    CTO Framework: Verification Phase
    - Dynamically fetches shortcuts from API endpoint
    - Tests each example from each shortcut
    - Verifies intent detection accuracy for authenticated users
    - Ensures no false positives/negatives
    - Outputs detailed results for each example
    """
    failures = []
    successes = []
    
    print(f"\n{'='*80}")
    print("CTO Framework: Intent Detection Verification")
    print(f"{'='*80}")
    print(f"Total shortcuts: {len(shortcuts_data)}")
    print(f"Conversation ID: {conversation_id}")
    print(f"{'='*80}\n")
    
    for shortcut in shortcuts_data:
        intent = shortcut["intent"]
        command = shortcut["command"]
        examples = shortcut.get("examples", [])
        
        print(f"\n📋 Testing Shortcut: {command} (intent: {intent})")
        print(f"   Examples to test: {len(examples)}")
        
        for idx, example in enumerate(examples, 1):
            print(f"   [{idx}/{len(examples)}] Testing: '{example}'")
            
            response = await client.post(
                f"/api/v1/user/chat/conversations/{conversation_id}/messages",
                json={"content": example, "language": "en"},
                headers={"Authorization": f"Bearer {ACCESS_TOKEN}"},
            )
            
            # Accept both 200 (existing conversation) and 201 (new conversation created)
            assert response.status_code in [200, 201], (
                f"Failed for {intent}: {example} - Status: {response.status_code}"
            )
            data = response.json()
            
            detected_intent = data.get("routing", {}).get("intent", "unknown")
            agent_content = data.get("agent_message", {}).get("content", "")
            
            if detected_intent == intent:
                print(f"      ✅ Intent correct: {detected_intent}")
                successes.append({
                    "shortcut": command,
                    "intent": intent,
                    "example": example,
                    "detected": detected_intent,
                })
            else:
                print(f"      ❌ Intent mismatch: expected '{intent}', got '{detected_intent}'")
                print(f"      Content preview: {agent_content[:80]}...")
                failures.append({
                    "shortcut": command,
                    "intent": intent,
                    "example": example,
                    "detected": detected_intent,
                    "content_preview": agent_content[:100],
                })
    
    print(f"\n{'='*80}")
    print(f"Results: {len(successes)} passed, {len(failures)} failed")
    print(f"{'='*80}\n")
    
    if failures:
        error_msg = "\n".join(
            [
                f"❌ {f['shortcut']} ({f['intent']}): '{f['example']}' → detected as '{f['detected']}'"
                for f in failures
            ]
        )
        pytest.fail(f"Intent detection failures:\n{error_msg}")


@pytest.mark.asyncio
@pytest.mark.integration
async def test_user_shortcut_examples_not_generic_fallback(
    client: AsyncClient,
    shortcuts_data: list,
    conversation_id: str,
):
    """
    Test that all shortcut examples return meaningful responses, not generic fallback.
    
    CTO Framework: Validation Phase
    - Dynamically fetches shortcuts from API endpoint
    - Tests each example from each shortcut
    - Verifies responses are contextually relevant for authenticated users
    - Ensures no generic "I'm your AI assistant" messages
    - Outputs detailed results for each example
    """
    failures = []
    successes = []
    
    print(f"\n{'='*80}")
    print("CTO Framework: Generic Fallback Validation")
    print(f"{'='*80}")
    print(f"Total shortcuts: {len(shortcuts_data)}")
    print(f"{'='*80}\n")
    
    for shortcut in shortcuts_data:
        intent = shortcut["intent"]
        command = shortcut["command"]
        examples = shortcut.get("examples", [])
        
        print(f"\n📋 Testing Shortcut: {command} (intent: {intent})")
        
        for idx, example in enumerate(examples, 1):
            print(f"   [{idx}/{len(examples)}] Testing: '{example}'")
            
            response = await client.post(
                f"/api/v1/user/chat/conversations/{conversation_id}/messages",
                json={"content": example, "language": "en"},
                headers={"Authorization": f"Bearer {ACCESS_TOKEN}"},
            )
            
            # Accept both 200 (existing conversation) and 201 (new conversation created)
            assert response.status_code in [200, 201], (
                f"Failed for {intent}: {example} - Status: {response.status_code}"
            )
            data = response.json()
            
            content = data.get("agent_message", {}).get("content", "")
            
            # Check if response is generic fallback
            if GENERIC_FALLBACK_MESSAGE in content:
                print(f"      ❌ Generic fallback detected")
                print(f"      Content: {content[:100]}...")
                failures.append({
                    "shortcut": command,
                    "intent": intent,
                    "example": example,
                    "content_preview": content[:100],
                })
            else:
                print(f"      ✅ Meaningful response (length: {len(content)})")
                print(f"      Preview: {content[:80]}...")
                successes.append({
                    "shortcut": command,
                    "intent": intent,
                    "example": example,
                })
    
    print(f"\n{'='*80}")
    print(f"Results: {len(successes)} passed, {len(failures)} failed")
    print(f"{'='*80}\n")
    
    if failures:
        error_msg = "\n".join(
            [
                f"❌ {f['shortcut']} ({f['intent']}): '{f['example']}' → Generic fallback detected"
                for f in failures
            ]
        )
        pytest.fail(f"Generic fallback detected for:\n{error_msg}")


@pytest.mark.asyncio
@pytest.mark.integration
async def test_user_shortcut_examples_have_meaningful_content(
    client: AsyncClient,
    shortcuts_data: list,
    conversation_id: str,
):
    """
    Test that all shortcut examples return responses with meaningful content.
    
    CTO Framework: Quality Assurance Phase
    - Dynamically fetches shortcuts from API endpoint
    - Tests each example from each shortcut
    - Verifies responses contain relevant information
    - Ensures minimum content length
    - Checks for intent-specific keywords
    - Outputs detailed results for each example
    """
    failures = []
    successes = []
    
    # Intent-specific keywords that should appear in responses
    intent_keywords = {
        "lending": ["lending", "vault", "yield", "morpho", "deposit"],
        "money_market": ["aave", "compound", "rate", "supply", "lending"],
        "swap": ["swap", "quote", "rate", "bridge", "exchange"],
        "portfolio": ["portfolio", "dashboard", "holdings", "assets", "tokens"],
        "balance": ["balance", "wallet", "account", "required"],
        "activity": ["transaction", "history", "activity", "account", "required"],
        "receive": ["address", "wallet", "receive", "deposit", "required"],
        "buy": ["buy", "crypto", "card", "account", "required"],
        "send": ["send", "transfer", "wallet", "account", "required"],
    }
    
    print(f"\n{'='*80}")
    print("CTO Framework: Content Quality Assurance")
    print(f"{'='*80}")
    print(f"Total shortcuts: {len(shortcuts_data)}")
    print(f"{'='*80}\n")
    
    for shortcut in shortcuts_data:
        intent = shortcut["intent"]
        command = shortcut["command"]
        examples = shortcut.get("examples", [])
        
        print(f"\n📋 Testing Shortcut: {command} (intent: {intent})")
        
        for idx, example in enumerate(examples, 1):
            print(f"   [{idx}/{len(examples)}] Testing: '{example}'")
            
            response = await client.post(
                f"/api/v1/user/chat/conversations/{conversation_id}/messages",
                json={"content": example, "language": "en"},
                headers={"Authorization": f"Bearer {ACCESS_TOKEN}"},
            )
            
            # Accept both 200 (existing conversation) and 201 (new conversation created)
            assert response.status_code in [200, 201], (
                f"Failed for {intent}: {example} - Status: {response.status_code}"
            )
            data = response.json()
            
            content = data.get("agent_message", {}).get("content", "").lower()
            
            # Check minimum content length
            if len(content) < 50:
                print(f"      ❌ Content too short: {len(content)} chars")
                failures.append({
                    "shortcut": command,
                    "intent": intent,
                    "example": example,
                    "issue": "Content too short",
                    "length": len(content),
                })
                continue
            
            # Check for intent-specific keywords
            if intent in intent_keywords:
                keywords = intent_keywords[intent]
                found_keyword = any(keyword in content for keyword in keywords)
                
                if not found_keyword:
                    print(f"      ❌ No intent keywords found (expected: {keywords})")
                    print(f"      Content: {content[:100]}...")
                    failures.append({
                        "shortcut": command,
                        "intent": intent,
                        "example": example,
                        "issue": "No intent-specific keywords found",
                        "expected_keywords": keywords,
                        "content_preview": content[:150],
                    })
                else:
                    print(f"      ✅ Content quality OK (length: {len(content)}, keywords found)")
                    successes.append({
                        "shortcut": command,
                        "intent": intent,
                        "example": example,
                    })
            else:
                # No specific keywords defined, just check length
                print(f"      ✅ Content quality OK (length: {len(content)})")
                successes.append({
                    "shortcut": command,
                    "intent": intent,
                    "example": example,
                })
    
    print(f"\n{'='*80}")
    print(f"Results: {len(successes)} passed, {len(failures)} failed")
    print(f"{'='*80}\n")
    
    if failures:
        error_msg = "\n".join(
            [
                f"❌ {f['shortcut']} ({f['intent']}): '{f['example']}' → {f['issue']}"
                for f in failures
            ]
        )
        pytest.fail(f"Content quality issues:\n{error_msg}")


@pytest.mark.asyncio
@pytest.mark.integration
async def test_user_shortcut_examples_comprehensive_output(
    client: AsyncClient,
    shortcuts_data: list,
    conversation_id: str,
):
    """
    Comprehensive test that verifies output for each example of each shortcut.
    
    CTO Framework: Comprehensive Verification Phase
    - Dynamically fetches shortcuts from API endpoint
    - Tests each example from each shortcut
    - Verifies complete response structure
    - Outputs detailed information for each example
    - Validates all response fields
    """
    print(f"\n{'='*80}")
    print("CTO Framework: Comprehensive Output Verification")
    print(f"{'='*80}")
    print(f"Total shortcuts: {len(shortcuts_data)}")
    print(f"Conversation ID: {conversation_id}")
    print(f"{'='*80}\n")
    
    all_results = []
    
    for shortcut in shortcuts_data:
        intent = shortcut["intent"]
        command = shortcut["command"]
        description = shortcut.get("description", "")
        examples = shortcut.get("examples", [])
        
        print(f"\n{'='*80}")
        print(f"Shortcut: {command}")
        print(f"Intent: {intent}")
        print(f"Description: {description}")
        print(f"Examples: {len(examples)}")
        print(f"{'='*80}")
        
        shortcut_results = {
            "shortcut": command,
            "intent": intent,
            "description": description,
            "examples": [],
        }
        
        for idx, example in enumerate(examples, 1):
            print(f"\n  Example {idx}/{len(examples)}: '{example}'")
            
            response = await client.post(
                f"/api/v1/user/chat/conversations/{conversation_id}/messages",
                json={"content": example, "language": "en"},
                headers={"Authorization": f"Bearer {ACCESS_TOKEN}"},
            )
            
            # Accept both 200 and 201
            assert response.status_code in [200, 201], (
                f"Failed for {intent}: {example} - Status: {response.status_code}"
            )
            
            data = response.json()
            
            # Extract key information
            detected_intent = data.get("routing", {}).get("intent", "unknown")
            agent_content = data.get("agent_message", {}).get("content", "")
            routing_info = data.get("routing", {})
            enrichment = data.get("enrichment", {})
            
            # Verify response structure
            assert "agent_message" in data, "Response missing 'agent_message'"
            assert "routing" in data, "Response missing 'routing'"
            
            # Build result
            result = {
                "example": example,
                "status_code": response.status_code,
                "detected_intent": detected_intent,
                "content_length": len(agent_content),
                "content_preview": agent_content[:150],
                "routing": routing_info,
                "has_enrichment": bool(enrichment),
                "is_generic_fallback": GENERIC_FALLBACK_MESSAGE in agent_content,
            }
            
            shortcut_results["examples"].append(result)
            
            # Print detailed output
            print(f"    Status: {response.status_code}")
            print(f"    Detected Intent: {detected_intent} {'✅' if detected_intent == intent else '❌'}")
            print(f"    Content Length: {len(agent_content)} chars")
            print(f"    Generic Fallback: {'Yes ❌' if result['is_generic_fallback'] else 'No ✅'}")
            print(f"    Has Enrichment: {'Yes' if result['has_enrichment'] else 'No'}")
            print(f"    Content Preview: {agent_content[:100]}...")
            
            if enrichment:
                print(f"    Enrichment Keys: {list(enrichment.keys())}")
        
        all_results.append(shortcut_results)
    
    # Summary
    print(f"\n{'='*80}")
    print("SUMMARY")
    print(f"{'='*80}")
    
    total_examples = sum(len(r["examples"]) for r in all_results)
    intent_correct = sum(
        1 for r in all_results
        for e in r["examples"]
        if e["detected_intent"] == r["intent"]
    )
    no_fallback = sum(
        1 for r in all_results
        for e in r["examples"]
        if not e["is_generic_fallback"]
    )
    
    print(f"Total Shortcuts: {len(all_results)}")
    print(f"Total Examples: {total_examples}")
    print(f"Intent Detection: {intent_correct}/{total_examples} ({intent_correct*100//total_examples}%)")
    print(f"No Generic Fallback: {no_fallback}/{total_examples} ({no_fallback*100//total_examples}%)")
    print(f"{'='*80}\n")
    
    # Verify all examples passed
    intent_failures = [
        (r["shortcut"], e["example"], e["detected_intent"], r["intent"])
        for r in all_results
        for e in r["examples"]
        if e["detected_intent"] != r["intent"]
    ]
    
    fallback_failures = [
        (r["shortcut"], e["example"])
        for r in all_results
        for e in r["examples"]
        if e["is_generic_fallback"]
    ]
    
    if intent_failures:
        error_msg = "\n".join(
            [
                f"❌ {shortcut} ({expected}): '{example}' → detected as '{detected}'"
                for shortcut, example, detected, expected in intent_failures
            ]
        )
        pytest.fail(f"Intent detection failures:\n{error_msg}")
    
    if fallback_failures:
        error_msg = "\n".join(
            [
                f"❌ {shortcut}: '{example}' → Generic fallback detected"
                for shortcut, example in fallback_failures
            ]
        )
        pytest.fail(f"Generic fallback detected for:\n{error_msg}")
