"""
Integration Test: Verify All Shortcut Examples Work for Authenticated Users

Tests all examples from the shortcuts endpoint for authenticated users to ensure:
1. Intent detection works correctly
2. Responses are not generic fallback messages
3. All shortcuts provide meaningful responses
4. Uses real access token from database (ops@anvilcrypto.com)

Follows CTO Engineering Framework methodology.
Based on test_all_shortcuts_examples.py but for authenticated users.

Generated by scripts/generate_user_tests.py
"""

import pytest
import pytest_asyncio
from httpx import AsyncClient, ASGITransport
from uuid import uuid4

from app.run import make_app

# Access token for ops@anvilcrypto.com (embedded from database)
ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Nlc3Npb25faWQiOiJxSEZBY1Mxd2RMN0lkWEx3aGQyb3pKYjdmeTFvd1lMUTZWci1OdkFJYWRFIiwiZXhwIjoxNzY3ODE3Mzk2fQ.qFnOS9hWQF4svpnxWe8YKDYFerQNKJSyGrYXhoSqHdQ"

# Generic fallback message that should NOT appear
GENERIC_FALLBACK_MESSAGE = (
    "I'm your AI assistant for DeFi! I can help with market analysis (Hunter AI), "
    "automated trading (ULTRA), lending rates, swaps, and more. "
    "Ask me about protocols, yields, risks, or how to get started. "
    "Sign up for full access to all features."
)


@pytest_asyncio.fixture
async def client():
    """Create test client."""
    app = make_app()
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        yield ac


@pytest_asyncio.fixture
async def conversation_id(client: AsyncClient):
    """Create or get conversation for authenticated user."""
    # Try to get existing conversation first
    response = await client.get(
        "/api/v1/user/chat/conversations",
        headers={"Authorization": f"Bearer {ACCESS_TOKEN}"},
    )
    
    if response.status_code == 200:
        conversations = response.json()
        if conversations and len(conversations) > 0:
            return conversations[0]["id"]
    
    # Create new conversation
    response = await client.post(
        "/api/v1/user/chat/conversations",
        json={"title": "Test Conversation", "language": "en"},
        headers={"Authorization": f"Bearer {eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Nlc3Npb25faWQiOiJxSEZBY1Mxd2RMN0lkWEx3aGQyb3pKYjdmeTFvd1lMUTZWci1OdkFJYWRFIiwiZXhwIjoxNzY3ODE3Mzk2fQ.qFnOS9hWQF4svpnxWe8YKDYFerQNKJSyGrYXhoSqHdQ}"},
    )
    
    if response.status_code == 201:
        return response.json()["id"]
    
    # Fallback: generate UUID (will be auto-created by endpoint)
    return str(uuid4())


@pytest_asyncio.fixture
async def shortcuts_data(client: AsyncClient):
    """Fetch shortcuts data from API."""
    response = await client.get("/api/v1/chat/shortcuts?lang=en")
    assert response.status_code == 200
    data = response.json()
    return data["shortcuts"]


@pytest.mark.asyncio
@pytest.mark.integration
async def test_user_shortcut_examples_detect_correct_intent(
    client: AsyncClient,
    shortcuts_data: list,
    conversation_id: str,
):
    """
    Test that all shortcut examples detect the correct intent for authenticated users.
    
    CTO Framework: Verification Phase
    - Verify intent detection accuracy for authenticated users
    - Ensure no false positives/negatives
    """
    failures = []
    
    for shortcut in shortcuts_data:
        intent = shortcut["intent"]
        command = shortcut["command"]
        
        for example in shortcut["examples"]:
            response = await client.post(
                f"/api/v1/user/chat/conversations/{{conversation_id}}/messages",
                json={'content': example, 'language': 'en'},
                headers={'Authorization': f'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Nlc3Npb25faWQiOiJxSEZBY1Mxd2RMN0lkWEx3aGQyb3pKYjdmeTFvd1lMUTZWci1OdkFJYWRFIiwiZXhwIjoxNzY3ODE3Mzk2fQ.qFnOS9hWQF4svpnxWe8YKDYFerQNKJSyGrYXhoSqHdQ'},
            )
            
            assert response.status_code == 200, f"Failed for {{intent}}: {{example}}"
            data = response.json()
            
            detected_intent = data["routing"]["intent"]
            
            if detected_intent != intent:
                failures.append(
                    {{
                        "shortcut": command,
                        "intent": intent,
                        "example": example,
                        "detected": detected_intent,
                    }}
                )
    
    if failures:
        error_msg = "\n".join(
            [
                f"❌ {{f['shortcut']}} ({{f['intent']}}): '{{f['example']}}' → detected as '{{f['detected']}}'"
                for f in failures
            ]
        )
        pytest.fail(f"Intent detection failures:\n{{error_msg}}")


@pytest.mark.asyncio
@pytest.mark.integration
async def test_user_shortcut_examples_not_generic_fallback(
    client: AsyncClient,
    shortcuts_data: list,
    conversation_id: str,
):
    """
    Test that all shortcut examples return meaningful responses, not generic fallback.
    
    CTO Framework: Validation Phase
    - Verify responses are contextually relevant for authenticated users
    - Ensure no generic "I'm your AI assistant" messages
    """
    failures = []
    
    for shortcut in shortcuts_data:
        intent = shortcut["intent"]
        command = shortcut["command"]
        
        for example in shortcut["examples"]:
            response = await client.post(
                f"/api/v1/user/chat/conversations/{{conversation_id}}/messages",
                json={'content': example, 'language': 'en'},
                headers={'Authorization': f'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Nlc3Npb25faWQiOiJxSEZBY1Mxd2RMN0lkWEx3aGQyb3pKYjdmeTFvd1lMUTZWci1OdkFJYWRFIiwiZXhwIjoxNzY3ODE3Mzk2fQ.qFnOS9hWQF4svpnxWe8YKDYFerQNKJSyGrYXhoSqHdQ'},
            )
            
            assert response.status_code == 200, f"Failed for {{intent}}: {{example}}"
            data = response.json()
            
            content = data["agent_message"]["content"]
            
            # Check if response is generic fallback
            if GENERIC_FALLBACK_MESSAGE in content:
                failures.append(
                    {{
                        "shortcut": command,
                        "intent": intent,
                        "example": example,
                        "content_preview": content[:100],
                    }}
                )
    
    if failures:
        error_msg = "\n".join(
            [
                f"❌ {{f['shortcut']}} ({{f['intent']}}): '{{f['example']}}' → Generic fallback detected"
                for f in failures
            ]
        )
        pytest.fail(f"Generic fallback detected for:\n{{error_msg}}")


@pytest.mark.asyncio
@pytest.mark.integration
async def test_user_shortcut_examples_have_meaningful_content(
    client: AsyncClient,
    shortcuts_data: list,
    conversation_id: str,
):
    """
    Test that all shortcut examples return responses with meaningful content.
    
    CTO Framework: Quality Assurance Phase
    - Verify responses contain relevant information
    - Ensure minimum content length
    - Check for intent-specific keywords
    """
    failures = []
    
    # Intent-specific keywords that should appear in responses
    intent_keywords = {{
        "lending": ["lending", "vault", "yield", "morpho", "deposit"],
        "money_market": ["aave", "compound", "rate", "supply", "lending"],
        "swap": ["swap", "quote", "rate", "bridge", "exchange"],
        "portfolio": ["portfolio", "dashboard", "holdings", "assets", "tokens"],
        "balance": ["balance", "wallet", "account"],
        "activity": ["transaction", "history", "activity"],
        "receive": ["address", "wallet", "receive", "deposit"],
        "buy": ["buy", "crypto", "card"],
        "send": ["send", "transfer", "wallet"],
    }}
    
    for shortcut in shortcuts_data:
        intent = shortcut["intent"]
        command = shortcut["command"]
        
        for example in shortcut["examples"]:
            response = await client.post(
                f"/api/v1/user/chat/conversations/{{conversation_id}}/messages",
                json={'content': example, 'language': 'en'},
                headers={'Authorization': f'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Nlc3Npb25faWQiOiJxSEZBY1Mxd2RMN0lkWEx3aGQyb3pKYjdmeTFvd1lMUTZWci1OdkFJYWRFIiwiZXhwIjoxNzY3ODE3Mzk2fQ.qFnOS9hWQF4svpnxWe8YKDYFerQNKJSyGrYXhoSqHdQ'},
            )
            
            assert response.status_code == 200, f"Failed for {{intent}}: {{example}}"
            data = response.json()
            
            content = data["agent_message"]["content"].lower()
            
            # Check minimum content length
            if len(content) < 50:
                failures.append(
                    {{
                        "shortcut": command,
                        "intent": intent,
                        "example": example,
                        "issue": "Content too short",
                        "length": len(content),
                    }}
                )
                continue
            
            # Check for intent-specific keywords
            if intent in intent_keywords:
                keywords = intent_keywords[intent]
                found_keyword = any(keyword in content for keyword in keywords)
                
                if not found_keyword:
                    failures.append(
                        {{
                            "shortcut": command,
                            "intent": intent,
                            "example": example,
                            "issue": "No intent-specific keywords found",
                            "expected_keywords": keywords,
                            "content_preview": content[:150],
                        }}
                    )
    
    if failures:
        error_msg = "\n".join(
            [
                f"❌ {{f['shortcut']}} ({{f['intent']}}): '{{f['example']}}' → {{f['issue']}}"
                for f in failures
            ]
        )
        pytest.fail(f"Content quality issues:\n{{error_msg}}")
