{
    "user_message": {
        "id": "8e125a61-2722-4795-a830-8615f2b9fd8d",
        "conversation_id": "892f31e9-f895-477a-8115-1f7b244e6ef5",
        "role": "user",
        "content": "Swap SOL to USDC",
        "agent_type": null,
        "created_at": "2026-01-10T15:23:30.717985+00:00"
    },
    "agent_message": {
        "id": "da7ce5d7-4c7b-45e1-9e51-52aee9c954ee",
        "conversation_id": "892f31e9-f895-477a-8115-1f7b244e6ef5",
        "role": "assistant",
        "content": "🔄 **Token Swap**\n\nYou want to swap:\n• **1 USDC** → **USDC**\n• Chain: BASE\n\n**Available DEX Aggregators:**\n• **1inch** - Best rates for single-chain swaps\n• **LiFi** - Cross-chain bridges and swaps\n• **Hyperliquid** - Perpetuals and spot trading\n\nTo get live quotes, configure the aggregator API keys.\n\n**Manual swap options:**\n• [1inch.io](https://1inch.io)\n• [LiFi](https://li.fi)\n• [Hyperliquid](https://hyperliquid.xyz)\n",
        "agent_type": null,
        "created_at": "2026-01-10T15:23:30.734053+00:00"
    },
    "routing": {
        "intent": "swap",
        "confidence": 0.99,
        "handler": "swap_handler",
        "agent_used": null,
        "reasoning": "User wants to exchange SOL for USDC",
        "total_latency_ms": 4492,
        "language": "en"
    },
    "enrichment": {
        "protocols": null,
        "search_context": null,
        "recommendations": null,
        "risk_analysis": null,
        "alternatives_count": null,
        "base_protocol": null,
        "similar_protocols": null,
        "task_type": null,
        "has_tools_used": null,
        "tools_used": null,
        "tokens_consumed": null,
        "latency_ms": 0,
        "intent_classification": null,
        "workflow_id": null,
        "workflow_status": null,
        "tasks_count": null,
        "agents_involved": null,
        "workflow_type": null,
        "total_latency_ms": null,
        "hunter_tool": null,
        "token_symbol": null,
        "tokens": null,
        "time_horizon": null,
        "sources": null,
        "risk_tolerance": null,
        "ultra_tool": null,
        "capital": null,
        "arb_type": null,
        "amount": null,
        "protocol": null,
        "opportunity_id": null,
        "action": null,
        "wallet_address": null,
        "ens_handle": null,
        "chain": "base",
        "supported_networks": null
    },
    "sources": [],
    "execute": null
}
