"""initial_schema

Revision ID: c6c70e02e562
Revises:
Create Date: 2026-02-06 17:18:26.455121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6c70e02e562"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_cost_daily")
    op.drop_table("llm_business_config")
    op.drop_index(op.f("idx_circuit_breakers_entity"), table_name="circuit_breakers")
    op.drop_index(
        op.f("idx_circuit_breakers_state"),
        table_name="circuit_breakers",
        postgresql_where="((state)::text <> 'closed'::text)",
    )
    op.drop_table("circuit_breakers")
    op.drop_table("custom_agent_configs")
    op.drop_table("template_executions")
    op.drop_table("ranking_weight_profiles")
    op.drop_table("conversation_exports")
    op.drop_table("agent_performance_metrics")
    op.drop_table("llm_budget_alerts")
    op.drop_table("voting_rounds")
    op.drop_index(op.f("idx_requests_agent"), table_name="llm_requests")
    op.drop_index(op.f("idx_requests_model"), table_name="llm_requests")
    op.drop_index(op.f("idx_requests_provider"), table_name="llm_requests")
    op.drop_index(op.f("idx_requests_status"), table_name="llm_requests")
    op.drop_index(op.f("idx_requests_user"), table_name="llm_requests")
    op.drop_table("llm_requests")
    op.drop_index(
        op.f("idx_cache_expiry"),
        table_name="llm_response_cache",
        postgresql_where="(expires_at IS NOT NULL)",
    )
    op.drop_index(op.f("idx_cache_key"), table_name="llm_response_cache")
    op.drop_table("llm_response_cache")
    op.drop_table("llm_cost_budgets")
    op.drop_table("agent_debates")
    op.drop_index(op.f("idx_audit_actor"), table_name="llm_audit_log")
    op.drop_index(op.f("idx_audit_entity"), table_name="llm_audit_log")
    op.drop_table("llm_audit_log")
    op.drop_index(
        op.f("idx_models_capabilities"), table_name="llm_models", postgresql_using="gin"
    )
    op.drop_index(
        op.f("idx_models_provider_enabled"),
        table_name="llm_models",
        postgresql_where="(is_enabled = true)",
    )
    op.drop_table("llm_models")
    op.drop_index(op.f("idx_telemetry_agent"), table_name="llm_telemetry_hourly")
    op.drop_index(op.f("idx_telemetry_lookup"), table_name="llm_telemetry_hourly")
    op.drop_table("llm_telemetry_hourly")
    op.drop_table("conversation_templates")
    op.drop_index(op.f("idx_attempts_request"), table_name="llm_request_attempts")
    op.drop_table("llm_request_attempts")
    op.drop_index(
        op.f("idx_providers_priority"),
        table_name="llm_providers",
        postgresql_where="(is_enabled = true)",
    )
    op.drop_table("llm_providers")
    op.drop_index(
        op.f("idx_distillation_telemetry_created_at"),
        table_name="distillation_telemetry",
    )
    op.drop_index(
        op.f("idx_distillation_telemetry_provider"), table_name="distillation_telemetry"
    )
    op.drop_index(
        op.f("idx_distillation_telemetry_success"), table_name="distillation_telemetry"
    )
    op.drop_index(
        op.f("idx_distillation_telemetry_timestamp"),
        table_name="distillation_telemetry",
    )
    op.drop_index(
        op.f("idx_distillation_telemetry_user_id"), table_name="distillation_telemetry"
    )
    op.drop_table("distillation_telemetry")
    op.drop_table("user_chat_preferences")
    op.drop_index(op.f("idx_analytics_snapshot_date"), table_name="analytics_snapshots")
    op.drop_index(op.f("idx_analytics_snapshot_type"), table_name="analytics_snapshots")
    op.drop_table("analytics_snapshots")
    op.drop_index(op.f("idx_rankings_agent_score"), table_name="agent_model_rankings")
    op.drop_table("agent_model_rankings")
    op.drop_table("ranking_overrides")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ranking_overrides",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "agent_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("model_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "override_score",
            sa.NUMERIC(precision=5, scale=4),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "override_score >= 0::numeric AND override_score <= 1::numeric",
            name=op.f("ck_ranking_overrides_valid_override"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llm_models.id"],
            name=op.f("fk_ranking_overrides_model_id_llm_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_overrides")),
    )
    op.create_table(
        "agent_model_rankings",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "agent_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("model_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "ranking_score",
            sa.NUMERIC(precision=5, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "success_rate",
            sa.NUMERIC(precision=5, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "latency_score",
            sa.NUMERIC(precision=5, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cost_score",
            sa.NUMERIC(precision=5, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("total_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "successful_requests", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("failed_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("timeout_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("avg_latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("p95_latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "avg_cost_per_request",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_tokens_used", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_used_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_recalculated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "ranking_score >= 0::numeric AND ranking_score <= 1::numeric AND success_rate >= 0::numeric AND success_rate <= 1::numeric",
            name=op.f("ck_agent_model_rankings_valid_scores"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llm_models.id"],
            name=op.f("fk_agent_model_rankings_model_id_llm_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_model_rankings")),
    )
    op.create_index(
        op.f("idx_rankings_agent_score"),
        "agent_model_rankings",
        ["agent_type", sa.literal_column("ranking_score DESC")],
        unique=False,
    )
    op.create_table(
        "analytics_snapshots",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("snapshot_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "snapshot_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "portfolio_empty_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "portfolio_starter_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "portfolio_active_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "portfolio_whale_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "activity_new_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "activity_very_active_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "activity_active_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "activity_weekly_active_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "activity_monthly_active_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "activity_inactive_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "activity_reactivated_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "type_new_user_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type_casual_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type_trader_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type_yield_farmer_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type_power_user_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("total_users", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "total_executions", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "total_balance_usd",
            sa.NUMERIC(precision=20, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("exec_swap_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("exec_buy_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "exec_lending_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "exec_transfer_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "exec_cashout_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "additional_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_snapshots")),
        sa.UniqueConstraint(
            "snapshot_date",
            "snapshot_type",
            name=op.f("uq_analytics_snapshot_date_type"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_analytics_snapshot_type"),
        "analytics_snapshots",
        ["snapshot_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_analytics_snapshot_date"),
        "analytics_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    op.create_table(
        "user_chat_preferences",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "verbosity_level",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tone_style", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "response_format",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "preferred_language",
            sa.VARCHAR(length=10),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timezone", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "include_code_examples", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "include_references", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "notification_conversation_updates",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "notification_agent_responses",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "notification_daily_summary",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "notification_insight_alerts",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "display_theme", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "display_font_size", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "display_show_timestamps", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "display_show_agent_names",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "display_markdown_rendering",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "favorite_agents",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "blocked_agents",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("custom_instructions", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_chat_preferences")),
    )
    op.create_table(
        "distillation_telemetry",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "request_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "detected_language",
            sa.VARCHAR(length=10),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "provider", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("model", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("success", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("reason", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "latency_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tokens_used", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "cost_usd",
            sa.NUMERIC(precision=10, scale=8),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fallback_used",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_distillation_telemetry")),
    )
    op.create_index(
        op.f("idx_distillation_telemetry_user_id"),
        "distillation_telemetry",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_distillation_telemetry_timestamp"),
        "distillation_telemetry",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("idx_distillation_telemetry_success"),
        "distillation_telemetry",
        ["success"],
        unique=False,
    )
    op.create_index(
        op.f("idx_distillation_telemetry_provider"),
        "distillation_telemetry",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("idx_distillation_telemetry_created_at"),
        "distillation_telemetry",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "llm_providers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "display_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "health_status", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_health_check",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "health_check_interval_seconds",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "rate_limits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "health_status::text = ANY (ARRAY['healthy'::character varying, 'degraded'::character varying, 'down'::character varying]::text[])",
            name=op.f("ck_llm_providers_valid_health_status"),
        ),
        sa.CheckConstraint(
            "priority >= 1 AND priority <= 10",
            name=op.f("ck_llm_providers_valid_priority"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_providers")),
        sa.UniqueConstraint(
            "name",
            name=op.f("uq_llm_providers_name"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_providers_priority"),
        "llm_providers",
        ["priority"],
        unique=False,
        postgresql_where="(is_enabled = true)",
    )
    op.create_table(
        "llm_request_attempts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("request_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("attempt_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("provider_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("model_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("input_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("output_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "cost_usd",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "error_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "error_code", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['started'::character varying, 'completed'::character varying, 'failed'::character varying, 'timeout'::character varying, 'rate_limited'::character varying, 'cancelled'::character varying]::text[])",
            name=op.f("ck_llm_request_attempts_valid_attempt_status"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llm_models.id"],
            name=op.f("fk_llm_request_attempts_model_id_llm_models"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_providers.id"],
            name=op.f("fk_llm_request_attempts_provider_id_llm_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["llm_requests.id"],
            name=op.f("fk_llm_request_attempts_request_id_llm_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_request_attempts")),
    )
    op.create_index(
        op.f("idx_attempts_request"),
        "llm_request_attempts",
        ["request_id", "attempt_number"],
        unique=False,
    )
    op.create_table(
        "conversation_templates",
        sa.Column("template_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("is_system", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "steps",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tags", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "estimated_duration_minutes",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "difficulty_level",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("usage_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "avg_completion_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "avg_user_rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("template_id", name=op.f("pk_conversation_templates")),
    )
    op.create_table(
        "llm_telemetry_hourly",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "hour_bucket",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("provider_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("model_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "agent_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("total_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "successful_requests", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("failed_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("timeout_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("retried_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cached_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("latency_p50_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("latency_p95_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("latency_p99_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("avg_latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("min_latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("max_latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "total_input_tokens", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "total_output_tokens", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("avg_input_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "avg_output_tokens", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "total_cost_usd",
            sa.NUMERIC(precision=12, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_cost_per_request",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_time_to_first_token_ms",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cache_hit_rate",
            sa.NUMERIC(precision=5, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "retry_rate",
            sa.NUMERIC(precision=5, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llm_models.id"],
            name=op.f("fk_llm_telemetry_hourly_model_id_llm_models"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_providers.id"],
            name=op.f("fk_llm_telemetry_hourly_provider_id_llm_providers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_telemetry_hourly")),
    )
    op.create_index(
        op.f("idx_telemetry_lookup"),
        "llm_telemetry_hourly",
        [sa.literal_column("hour_bucket DESC"), "provider_id", "model_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_telemetry_agent"),
        "llm_telemetry_hourly",
        [sa.literal_column("hour_bucket DESC"), "agent_type"],
        unique=False,
    )
    op.create_table(
        "llm_models",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("provider_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "model_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "display_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "model_family", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("context_window", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "max_output_tokens", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "supports_streaming", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column("supports_tools", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "cost_per_1k_input",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cost_per_1k_output",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("avg_latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "carousel_position", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("tier", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "tier::text = ANY (ARRAY['premium'::character varying, 'standard'::character varying, 'economy'::character varying, 'experimental'::character varying]::text[])",
            name=op.f("ck_llm_models_valid_tier"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_providers.id"],
            name=op.f("fk_llm_models_provider_id_llm_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_models")),
    )
    op.create_index(
        op.f("idx_models_provider_enabled"),
        "llm_models",
        ["provider_id", "carousel_position"],
        unique=False,
        postgresql_where="(is_enabled = true)",
    )
    op.create_index(
        op.f("idx_models_capabilities"),
        "llm_models",
        ["capabilities"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "llm_audit_log",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "action_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "entity_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("entity_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("actor_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("actor_ip", postgresql.INET(), autoincrement=False, nullable=True),
        sa.Column(
            "before_value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "after_value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("change_reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_audit_log")),
    )
    op.create_index(
        op.f("idx_audit_entity"),
        "llm_audit_log",
        ["entity_type", "entity_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_audit_actor"),
        "llm_audit_log",
        ["actor_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_table(
        "agent_debates",
        sa.Column("debate_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("query", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "participating_agents",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "current_phase", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "consensus_status",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("final_consensus", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "consensus_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "statements",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("max_rounds", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("current_round", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("debate_id", name=op.f("pk_agent_debates")),
    )
    op.create_table(
        "llm_cost_budgets",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "budget_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "budget_amount_usd",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "warning_threshold_percent",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "critical_threshold_percent",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "current_spend_usd",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "period_start",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "period_end",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_hard_limit", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "notify_emails",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "notify_slack_channel",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_alert_sent_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "budget_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying]::text[])",
            name=op.f("ck_llm_cost_budgets_valid_budget_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_cost_budgets")),
    )
    op.create_table(
        "llm_response_cache",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "cache_key", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "agent_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "prompt_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column("model_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "temperature",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("response_content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("output_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hit_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_hit_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["llm_models.id"],
            name=op.f("fk_llm_response_cache_model_id_llm_models"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_response_cache")),
        sa.UniqueConstraint(
            "cache_key",
            name=op.f("uq_llm_response_cache_cache_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_cache_key"), "llm_response_cache", ["cache_key"], unique=False
    )
    op.create_index(
        op.f("idx_cache_expiry"),
        "llm_response_cache",
        ["expires_at"],
        unique=False,
        postgresql_where="(expires_at IS NOT NULL)",
    )
    op.create_table(
        "llm_requests",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "request_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "agent_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "prompt_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column("input_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "max_output_tokens", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "temperature",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("has_tools", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_streaming", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column(
            "status_history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "selected_provider_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column("selected_model_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "selection_reason",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("attempt_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("total_latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "time_to_first_token_ms", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("output_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "estimated_cost_usd",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "actual_cost_usd",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "error_code", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['pending'::character varying, 'queued'::character varying, 'selecting_model'::character varying, 'executing'::character varying, 'streaming'::character varying, 'completed'::character varying, 'failed'::character varying, 'timeout'::character varying, 'cancelled'::character varying, 'retrying'::character varying]::text[])",
            name=op.f("ck_llm_requests_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["selected_model_id"],
            ["llm_models.id"],
            name=op.f("fk_llm_requests_selected_model_id_llm_models"),
        ),
        sa.ForeignKeyConstraint(
            ["selected_provider_id"],
            ["llm_providers.id"],
            name=op.f("fk_llm_requests_selected_provider_id_llm_providers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_requests")),
        sa.UniqueConstraint(
            "request_id",
            name=op.f("uq_llm_requests_request_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_requests_user"),
        "llm_requests",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_requests_status"),
        "llm_requests",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_requests_provider"),
        "llm_requests",
        ["selected_provider_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_requests_model"),
        "llm_requests",
        ["selected_model_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_requests_agent"),
        "llm_requests",
        ["agent_type", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "voting_rounds",
        sa.Column("round_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("query", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "strategy", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column("winning_response", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "winning_vote_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("total_votes", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "consensus_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "votes",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("round_id", name=op.f("pk_voting_rounds")),
    )
    op.create_table(
        "llm_budget_alerts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("budget_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "alert_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "threshold_percent", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "current_spend_usd",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "budget_amount_usd",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "notified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "notification_channels",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["llm_cost_budgets.id"],
            name=op.f("fk_llm_budget_alerts_budget_id_llm_cost_budgets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_budget_alerts")),
    )
    op.create_table(
        "agent_performance_metrics",
        sa.Column(
            "agent_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("total_requests", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "successful_requests", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("failed_requests", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "avg_response_time_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "avg_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "avg_cost_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_cost_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "uptime_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_24h_requests", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("last_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_error_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint(
            "agent_name", name=op.f("pk_agent_performance_metrics")
        ),
    )
    op.create_table(
        "conversation_exports",
        sa.Column("export_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("format", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "include_metadata", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "include_timestamps", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "include_agent_names", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("redact_pii", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "compliance_standard",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("file_size_bytes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("download_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "requested_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("export_id", name=op.f("pk_conversation_exports")),
    )
    op.create_table(
        "ranking_weight_profiles",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "agent_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "success_weight",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "latency_weight",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cost_weight",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "recency_weight",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "min_requests_for_ranking", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "recency_decay_hours", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "(success_weight + latency_weight + cost_weight + recency_weight) = 1.00",
            name=op.f("ck_ranking_weight_profiles_weights_sum_to_one"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_weight_profiles")),
        sa.UniqueConstraint(
            "agent_type",
            name=op.f("uq_ranking_weight_profiles_agent_type"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "template_executions",
        sa.Column("execution_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("template_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "current_step_index", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "step_results",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "execution_time_seconds", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completion_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "paused_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("execution_id", name=op.f("pk_template_executions")),
    )
    op.create_table(
        "custom_agent_configs",
        sa.Column("config_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("system_prompt", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "capabilities",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "temperature",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("max_tokens", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "personality_traits",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expertise_areas",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "response_style", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "preferred_llm_provider",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fallback_llm_provider",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("config_id", name=op.f("pk_custom_agent_configs")),
    )
    op.create_table(
        "circuit_breakers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "entity_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("entity_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "entity_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("state", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("failure_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("success_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "consecutive_failures", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_failure_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_success_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "opened_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "half_open_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"timeout_seconds": 60, "failure_threshold": 5, "success_threshold": 3, "half_open_max_requests": 3}\'::jsonb'
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "state::text = ANY (ARRAY['closed'::character varying, 'open'::character varying, 'half_open'::character varying]::text[])",
            name=op.f("ck_circuit_breakers_valid_cb_state"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_circuit_breakers")),
    )
    op.create_index(
        op.f("idx_circuit_breakers_state"),
        "circuit_breakers",
        ["state"],
        unique=False,
        postgresql_where="((state)::text <> 'closed'::text)",
    )
    op.create_index(
        op.f("idx_circuit_breakers_entity"),
        "circuit_breakers",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "llm_business_config",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "config_key", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "config_value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "config_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("modified_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "previous_value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("change_reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "validation_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_business_config")),
        sa.UniqueConstraint(
            "config_key",
            name=op.f("uq_llm_business_config_config_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "llm_cost_daily",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("provider_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "total_cost_usd",
            sa.NUMERIC(precision=12, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("total_requests", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("total_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "premium_cost_usd",
            sa.NUMERIC(precision=12, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "standard_cost_usd",
            sa.NUMERIC(precision=12, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "economy_cost_usd",
            sa.NUMERIC(precision=12, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_providers.id"],
            name=op.f("fk_llm_cost_daily_provider_id_llm_providers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_cost_daily")),
    )
    # ### end Alembic commands ###
