"""
Wallet entity.

Represents a blockchain wallet associated with a user.
Supports multiple wallet types:
- PRIVY: Privy embedded wallet (has privy_wallet_id)
- EXTERNAL: External wallet (e.g., MetaMask)
- IMPORTED: Wallet imported via private key (privy_wallet_id is optional)

Privy Configuration Fields (for admin management):
- policy_ids: List of policy IDs attached to this wallet
- owner_type: Type of owner (user, authorization_key, etc.)
- owner_id: ID of the owner
- additional_signers: List of additional signers with their configurations
- exported_at: When the wallet was exported
- imported_at: When the wallet was imported
- last_privy_sync_at: Last time we synced with Privy API
"""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from app.domain.entities.base import Entity
from app.domain.enums.chain_type import ChainType
from app.domain.enums.wallet_provider import WalletProvider
from app.domain.enums.wallet_status import WalletStatus
from app.domain.value_objects.base import ValueObject
from app.domain.value_objects.created_at import CreatedAt
from app.domain.value_objects.updated_at import UpdatedAt
from app.domain.value_objects.user_id import UserId


@dataclass(frozen=True, repr=False)
class WalletId(ValueObject):
    value: int


@dataclass(frozen=True)
class AdditionalSigner:
    """Represents an additional signer for a wallet."""

    signer_id: str
    override_policy_ids: list[str] | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage."""
        result: dict[str, Any] = {"signer_id": self.signer_id}
        if self.override_policy_ids is not None:
            result["override_policy_ids"] = self.override_policy_ids
        return result

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AdditionalSigner":
        """Create from dictionary."""
        return cls(
            signer_id=data.get("signer_id", ""),
            override_policy_ids=data.get("override_policy_ids"),
        )


@dataclass(eq=False, kw_only=True)
class Wallet(Entity[WalletId]):
    user_id: UserId
    privy_wallet_id: str | None  # Can be None for imported wallets
    address: str
    provider: WalletProvider
    default_chain: ChainType
    status: WalletStatus
    created_at: CreatedAt
    updated_at: UpdatedAt

    # Privy configuration fields (for admin management)
    policy_ids: list[str] = field(default_factory=list)
    owner_type: str | None = None  # e.g., "user", "authorization_key"
    owner_id: str | None = None
    additional_signers: list[AdditionalSigner] = field(default_factory=list)
    exported_at: datetime | None = None
    imported_at: datetime | None = None
    last_privy_sync_at: datetime | None = None

    @classmethod
    def create(
        cls,
        user_id: UserId,
        address: str,
        provider: WalletProvider = WalletProvider.PRIVY,
        default_chain: ChainType = ChainType.ETHEREUM,
        privy_wallet_id: str | None = None,
        policy_ids: list[str] | None = None,
        owner_type: str | None = None,
        owner_id: str | None = None,
        additional_signers: list[AdditionalSigner] | None = None,
    ) -> "Wallet":
        """
        Create a new wallet entity.

        Args:
            user_id: The user who owns this wallet.
            address: Blockchain address (0x...).
            provider: Wallet provider (PRIVY, EXTERNAL, IMPORTED).
            default_chain: Default blockchain for this wallet.
            privy_wallet_id: Privy wallet ID (optional for imported wallets).
            policy_ids: List of policy IDs for this wallet.
            owner_type: Type of owner (user, authorization_key, etc.).
            owner_id: ID of the owner.
            additional_signers: List of additional signers.

        Returns:
            A new Wallet entity.
        """
        now = datetime.now(UTC)

        # Generate synthetic ID for imported wallets if not provided
        wallet_id = privy_wallet_id
        if wallet_id is None and provider == WalletProvider.IMPORTED:
            wallet_id = f"imported:{address.lower()}"

        return cls(
            id_=WalletId(0),  # ID generated by DB
            user_id=user_id,
            privy_wallet_id=wallet_id,
            address=address.lower(),  # Normalize address
            provider=provider,
            default_chain=default_chain,
            status=WalletStatus.ACTIVE,
            created_at=CreatedAt(now),
            updated_at=UpdatedAt(now),
            policy_ids=policy_ids or [],
            owner_type=owner_type,
            owner_id=owner_id,
            additional_signers=additional_signers or [],
        )

    @classmethod
    def create_imported(
        cls,
        user_id: UserId,
        address: str,
        default_chain: ChainType = ChainType.ETHEREUM,
    ) -> "Wallet":
        """
        Create an imported wallet entity.

        Convenience method for creating imported wallets.

        Args:
            user_id: The user who owns this wallet.
            address: Blockchain address (0x...).
            default_chain: Default blockchain for this wallet.

        Returns:
            A new Wallet entity with provider=IMPORTED.
        """
        return cls.create(
            user_id=user_id,
            address=address,
            provider=WalletProvider.IMPORTED,
            default_chain=default_chain,
            privy_wallet_id=None,
        )
