"""
Wallet entity.
"""
from dataclasses import dataclass
from typing import Optional
from datetime import datetime
import uuid

from app.domain.entities.base import Entity
from app.domain.value_objects.user_id import UserId
from app.domain.value_objects.base import ValueObject
from app.domain.enums.wallet_provider import WalletProvider
from app.domain.enums.chain_type import ChainType
from app.domain.enums.wallet_status import WalletStatus
from app.domain.value_objects.created_at import CreatedAt
from app.domain.value_objects.updated_at import UpdatedAt

@dataclass(frozen=True, repr=False)
class WalletId(ValueObject):
    value: int

@dataclass(eq=False, kw_only=True)
class Wallet(Entity[WalletId]):
    user_id: UserId
    privy_wallet_id: str
    address: str
    provider: WalletProvider
    default_chain: ChainType
    status: WalletStatus
    created_at: CreatedAt
    updated_at: UpdatedAt

    @classmethod
    def create(
        cls,
        user_id: UserId,
        privy_wallet_id: str,
        address: str,
        provider: WalletProvider = WalletProvider.PRIVY,
        default_chain: ChainType = ChainType.ARBITRUM
    ) -> "Wallet":
        now = CreatedAt.now()
        return cls(
            id_=WalletId(0), # ID generated by DB
            user_id=user_id,
            privy_wallet_id=privy_wallet_id,
            address=address,
            provider=provider,
            default_chain=default_chain,
            status=WalletStatus.ACTIVE,
            created_at=now,
            updated_at=UpdatedAt(now.value)
        )
