"""
Guest Auth Agent - Handles authentication requirements for restricted features.
"""

import time

from app.domain.enums.agent_type import AgentType
from app.domain.value_objects.conversation_id import ConversationId
from app.domain.value_objects.message_content import MessageContent
from app.domain.value_objects.agent_squad.conversation_context import ConversationContext
from app.domain.ports.agent_squad.agent_gateway import AgentGateway, AgentResponse
from app.domain.ports.agent_squad.llm_client_gateway import LLMClientGateway


class GuestAuthAgentOpenAI:
    """
    Guest Auth Agent implementation.
    
    Implements: AgentGateway
    
    Purpose: Handle authentication requirements for restricted features
    
    Capabilities:
    - Detect which restricted feature user is asking about
    - Return appropriate custom registration message
    - Support multiple languages
    - Provide clear sign-in instructions
    
    Model: gemini-2.0-flash (fast, cost-effective)
    Temperature: 0.3 (consistent responses)
    """
    
    def __init__(
        self,
        llm_client: LLMClientGateway,
        model: str = "gemini-2.0-flash",
        temperature: float = 0.3,
        max_tokens: int = 500,
    ):
        """Initialize guest auth agent."""
        self._llm_client = llm_client
        self._model = model
        self._temperature = temperature
        self._max_tokens = max_tokens
    
    @property
    def agent_type(self) -> AgentType:
        """Get agent type."""
        # Use CHAT type - supervisor will route restricted queries to this agent
        # The agent detects which restricted feature and returns custom message
        return AgentType.CHAT
    
    async def execute(
        self,
        conversation_id: ConversationId,
        message: MessageContent,
        conversation_context: ConversationContext,
    ) -> AgentResponse:
        """Execute guest auth agent - Return custom registration message."""
        start_time = time.time()
        
        # Detect which restricted feature the user is asking about
        restricted_feature = self._detect_restricted_feature(message.value)
        
        # Get custom message for this restricted feature
        custom_message = self._get_custom_message(restricted_feature, conversation_context)
        
        latency_ms = int((time.time() - start_time) * 1000)
        
        # Collect sources
        from datetime import datetime, UTC
        from app.domain.value_objects.chat.source_info import SourceInfo, SourceType
        
        sources = []
        fetched_at = datetime.now(UTC)
        
        # Add LLM source
        sources.append(SourceInfo(
            source_type=SourceType.LLM,
            source_name=self._model,
            citation_text=f"Generated by {self._model}",
            fetched_at=fetched_at,
            provider="Vertex AI" if "gemini" in self._model.lower() else "DeepInfra",
            metadata={"model": self._model, "restricted_feature": restricted_feature},
        ))
        
        return AgentResponse(
            content=custom_message,
            agent_type=self.agent_type,
            tools_used=["auth_detection"],
            sources=sources,
            metadata={
                "tokens_used": 0,  # No LLM call needed - using predefined messages
                "latency_ms": latency_ms,
                "model": self._model,
                "restricted_feature": restricted_feature,
                "provider": "vertex_ai" if "gemini" in self._model.lower() else "deepinfra",
            },
        )
    
    def _detect_restricted_feature(self, message: str) -> str:
        """Detect which restricted feature user is asking about."""
        message_lower = message.lower()
        
        # Priority order (most specific first)
        if any(kw in message_lower for kw in ["my balance", "what's my balance", "check my balance", "how much do i have", "wallet balance"]):
            return "balance"
        elif any(kw in message_lower for kw in ["my transactions", "transaction history", "show my activity", "recent activity", "my activity", "my trades"]):
            return "activity"
        elif any(kw in message_lower for kw in ["my address", "wallet address", "receive crypto", "deposit address", "QR code", "receive address", "i want to receive"]):
            return "receive"
        elif any(kw in message_lower for kw in ["buy crypto", "purchase bitcoin", "buy with card", "how to buy ETH", "i want to buy", "buy with fiat"]):
            return "buy"
        elif any(kw in message_lower for kw in ["send crypto", "transfer tokens", "send to wallet", "send to friend", "i want to send", "transfer crypto"]):
            return "send"
        elif any(kw in message_lower for kw in ["my portfolio", "my holdings", "list my tokens", "what tokens do i have", "show my holdings", "what tokens do i own"]):
            return "portfolio"
        else:
            return "general"  # Fallback
    
    def _get_custom_message(self, feature: str, context: ConversationContext) -> str:
        """Get custom registration message for restricted feature."""
        # Get language from context
        language = context.user_metadata.get("language", "en") if context.user_metadata else "en"
        
        # Import translation function
        from app.application.guest.i18n.translations import get_registration_message
        
        # Map feature to reason
        feature_to_reason = {
            "balance": "wallet_access",
            "activity": "transaction_history",
            "receive": "wallet_address",
            "buy": "buy_crypto",
            "send": "send_crypto",
            "portfolio": "portfolio_access",
            "general": "execute_action",  # Fallback
        }
        
        reason = feature_to_reason.get(feature, "execute_action")
        messages = get_registration_message(reason, language)
        message = messages.get(language, messages.get("en", ""))
        
        # Add CTA
        from app.application.guest.i18n.translations import get_cta_message
        cta = get_cta_message(language)
        
        return f"{message}\n\n👉 {cta}: /signup"
    
    async def is_available(self) -> bool:
        """Check if agent is available."""
        return True
