"""
Helper functions for source collection in agents.

Provides common patterns for collecting source information across agents.
"""

from datetime import datetime
from typing import Optional

from app.domain.value_objects.chat.source_info import SourceInfo, SourceType, sanitize_query_params


def create_llm_source(
    model: str,
    provider: Optional[str] = None,
    fetched_at: Optional[datetime] = None,
) -> SourceInfo:
    """
    Create LLM source information.
    
    Args:
        model: Model name (e.g., "gpt-4o", "gemini-2.0-flash-exp")
        provider: Provider name (e.g., "Vertex AI", "DeepInfra")
        fetched_at: Timestamp when data was fetched
        
    Returns:
        SourceInfo for LLM source
    """
    if not provider:
        # Auto-detect provider from model name
        if "gemini" in model.lower():
            provider = "Vertex AI"
        elif "llama" in model.lower() or "meta" in model.lower():
            provider = "DeepInfra"
        else:
            provider = "OpenAI"
    
    return SourceInfo(
        source_type=SourceType.LLM,
        source_name=model,
        citation_text=f"Generated by {model}",
        fetched_at=fetched_at or datetime.utcnow(),
        provider=provider,
        metadata={"model": model},
    )


def create_api_source(
    source_name: str,
    url: Optional[str] = None,
    endpoint: Optional[str] = None,
    query_params: Optional[dict] = None,
    citation_text: Optional[str] = None,
    fetched_at: Optional[datetime] = None,
    provider: Optional[str] = None,
    relevance_score: float = 1.0,
    data_points_used: Optional[int] = None,
    metadata: Optional[dict] = None,
) -> SourceInfo:
    """
    Create API source information.
    
    Args:
        source_name: API name (e.g., "CoinGecko", "1inch")
        url: Direct URL to source
        endpoint: API endpoint used
        query_params: Query parameters (will be sanitized)
        citation_text: Human-readable citation
        fetched_at: Timestamp when data was fetched
        provider: Provider name (defaults to source_name)
        relevance_score: Relevance score (0.0-1.0)
        data_points_used: Number of data points
        metadata: Additional metadata
        
    Returns:
        SourceInfo for API source
    """
    return SourceInfo(
        source_type=SourceType.API,
        source_name=source_name,
        url=url,
        endpoint=endpoint,
        query_params=sanitize_query_params(query_params) if query_params else None,
        citation_text=citation_text or f"Data from {source_name}",
        fetched_at=fetched_at or datetime.utcnow(),
        provider=provider or f"{source_name} API",
        relevance_score=relevance_score,
        data_points_used=data_points_used,
        metadata=metadata,
    )


def create_mcp_source(
    mcp_server_name: str,
    tool_name: Optional[str] = None,
    url: Optional[str] = None,
    citation_text: Optional[str] = None,
    fetched_at: Optional[datetime] = None,
    metadata: Optional[dict] = None,
) -> SourceInfo:
    """
    Create MCP server source information.
    
    Args:
        mcp_server_name: MCP server name (e.g., "Aave", "Morpho")
        tool_name: Tool name used (e.g., "get_markets")
        url: Direct URL to source (if available)
        citation_text: Human-readable citation
        fetched_at: Timestamp when data was fetched
        metadata: Additional metadata
        
    Returns:
        SourceInfo for MCP server source
    """
    endpoint = f"mcp://{mcp_server_name.lower()}/{tool_name}" if tool_name else f"mcp://{mcp_server_name.lower()}"
    
    return SourceInfo(
        source_type=SourceType.MCP_SERVER,
        source_name=mcp_server_name,
        url=url,
        endpoint=endpoint,
        citation_text=citation_text or f"Data from {mcp_server_name} MCP Server",
        fetched_at=fetched_at or datetime.utcnow(),
        provider=f"{mcp_server_name} MCP Server",
        metadata=metadata or {},
    )


def create_blockchain_source(
    chain: str,
    tx_hash: Optional[str] = None,
    contract_address: Optional[str] = None,
    explorer_url: Optional[str] = None,
    citation_text: Optional[str] = None,
    fetched_at: Optional[datetime] = None,
    metadata: Optional[dict] = None,
) -> SourceInfo:
    """
    Create blockchain source information.
    
    Args:
        chain: Chain name (e.g., "Ethereum", "Base")
        tx_hash: Transaction hash (if applicable)
        contract_address: Contract address (if applicable)
        explorer_url: Block explorer URL
        citation_text: Human-readable citation
        fetched_at: Timestamp when data was fetched
        metadata: Additional metadata
        
    Returns:
        SourceInfo for blockchain source
    """
    # Build explorer URL if not provided
    if not explorer_url and tx_hash:
        chain_lower = chain.lower()
        if chain_lower == "ethereum":
            explorer_url = f"https://etherscan.io/tx/{tx_hash}"
        elif chain_lower == "base":
            explorer_url = f"https://basescan.org/tx/{tx_hash}"
        elif chain_lower == "arbitrum":
            explorer_url = f"https://arbiscan.io/tx/{tx_hash}"
        elif chain_lower == "optimism":
            explorer_url = f"https://optimistic.etherscan.io/tx/{tx_hash}"
        elif chain_lower == "polygon":
            explorer_url = f"https://polygonscan.com/tx/{tx_hash}"
        else:
            explorer_url = None
    
    return SourceInfo(
        source_type=SourceType.BLOCKCHAIN,
        source_name=chain.title(),
        source_id=tx_hash or contract_address,
        url=explorer_url,
        citation_text=citation_text or f"On-chain data from {chain}",
        fetched_at=fetched_at or datetime.utcnow(),
        provider=f"{chain} RPC",
        metadata=metadata or {},
    )


def create_database_source(
    source_name: str = "Anvil Database",
    citation_text: Optional[str] = None,
    data_points_used: Optional[int] = None,
    fetched_at: Optional[datetime] = None,
    metadata: Optional[dict] = None,
) -> SourceInfo:
    """
    Create database source information.
    
    Args:
        source_name: Database name (default: "Anvil Database")
        citation_text: Human-readable citation
        data_points_used: Number of data points
        fetched_at: Timestamp when data was fetched
        metadata: Additional metadata
        
    Returns:
        SourceInfo for database source
    """
    return SourceInfo(
        source_type=SourceType.DATABASE,
        source_name=source_name,
        citation_text=citation_text or f"Data from {source_name}",
        fetched_at=fetched_at or datetime.utcnow(),
        provider="Anvil Backend",
        data_points_used=data_points_used,
        metadata=metadata or {},
    )
